from apyori import apriori
from readData import loadCSV


transactions = [
    ['ACETONA FARMAX 100ML', 'SH SEDA SOS CASPA 2EM1', 'DOCE BANANADA', 'DOCE DE BANANA C/ ABACAXI PCTE', 'CEBOLA',
     'BATATA'], ['MAC OVOS AVE MARIA', 'MAC OVOS ESPAGUETE 8 SANTA AMA', 'MAC OVOS FIDELINHO 10',
                 'MAC OVOS NINHO SANTA AMALIA FETUCCINE', 'MAC OVOS PADRE NOSSO',
                 'SAND HAV SLIM ANIMALIS 39/40 PPRETO/BRANCO', 'MAC OVOS PARAFUSO', 'MAC OVOS RIGATONE'],
    ['MAC OVOS TAGLIATELLE 10', 'MAC OVOS TORTELONI', 'MAC OVOS PARAFUSO TETRACOLOR',
     'DOCE DE LEITE PORTAO DE CAMBUI(VIDRO)', 'MAC INST TALHARIM A BOLONHESA',
     'DOCE LEITE C/COCO PORTAO CAMBUI (VIDRO)', 'MAIONESE SANTA AMALIA SACHE 200G', 'MIST BOLO SANTA AMALIA ABACAXI',
     'MISTURA SANTA AMALIA BOLO COCO', 'MISTURA DE BOLO CHO STA AMALIA', 'MISTURA ECON. BOLO FESTA',
     'MIST PAO DE QUEIJO SANTA AMALIA', 'MILHO PIPOCA MICRO NATURAL SANTA A'],
    ['SAND HAV SLIN FROZEN 29/30 LAVANDA', 'SAND HAV SLIM SEASON 35/6', 'SAND HAV SLIM CHOC 33/4',
     'SAND HAV SLIM HORT 37/8'],
    ['SHAMPOO TRESSSEME SELAGEM CAPILAR CRESPO ORIGINAL', 'CREME DENTAL SORRISO 90G', 'CREME JOHNHOS MEL E LINHAACA',
     'LINGUICA CANASTRA APIMENTADA', 'DES REXONA AER ACTIVE EMOTION', 'DES REXONA AEROSOL AQUASHIED',
     'DES HERBISSIMO CREME', 'DES REXONA POWDER', 'DES REXONA AER V8', 'PIRULITO POWER',
     'CREME DE TRATAMENTO DOVE OLEO NUTRICAO', 'DESINF PINHO SOL LAVANDA', 'DESINF PINHO SOL ORIGINAL 500 ML',
     'LUVA MUCAMBO G', 'LUVA MUCAMBO XG'],
    ['COOK  HOUSE', 'DET OMO PODER DO SOL 500G', 'DETER. OMO M.ACAO 1 KG', 'DET OMO TANQUINHO 1KG',
     'DET OMO CONFORT VIOLETA 1KG', 'DET OMO CONFORT CLASSIC 1KG'],
    ['MILHO PIPOCA MICRO BACON', 'CHOC KIT KAT', 'BISCOITO NESFIT COCO'],
    ['BALA ERLAN SORTIDA', 'DES HID VASENOL PELE RESSECADA', 'CR DENTAL COLGATE TOTAL CLEAN MINT',
     'CR DENTAL COLGATE TOTAL FRESH 90 GRS'],
    ['LING CALABRESA SADIA', 'MINI CHICKEN C. VALE', 'BOLINHO BAUDDUCO GOTAS CHOCOLATE'],
    ['LING SADIA', 'MINI CHICKEN SADIA', 'MORTANDELA SADILAR SADIA 1KG'],
    ['FRALDA EVOLUTION EG 64 UNIDADES', 'FRALDA EVOLUTION G 72 UNIDADES', 'FRALDA EVOLUTION M 80 UNIDADES'],
    ['CHIC BUBBALOO', 'DOCE DE AMENDOIM', 'CR DENTAL COLGATE TOTAL FRESH 90 GRS', 'CR DENTAL COLGATE TOTAL CLEAN MINT'],
    ['ALCOOL ECOFLAME 500ML', 'CALDO KNORR 114G GALINHA', 'CALDO KNORR GALINHA 57G', 'DETERG TIXAN 2 KG PRIMAVERA',
     'CREME HIDRATANTE NOVEX ANTI AGE', 'CR DENTAL SORRISO 180G', 'DET TIXAN MACIEZ 1 KG', 'ESPONJA ESREBOM',
     'ESPONJA BETTANIN C/ 4', 'FARINHA D MANDIOCA KI FLOR', 'SAB FRANCIS CX JASMIM DO MARROCOS', 'SH SEDA LISO EXTREMO',
     'SH SEDA OLEO HIDRATACAO', 'BALA FINI (TORCAO)', 'BALA FINI TUBES (TROLLS)', 'VINAGRE TOSCANO MACA'],
    ['ARROZ CODIL T1', 'MISSIN CUP NOODEES CARNE', 'FAROFA MANDIOCA KI -FLOR', 'FEIJAO PRETO CODIL'],
    ['DES DOVE ORIGINAL', 'DES REXONA AEROSOL MEN ACTIVE', 'LEITE COND PIRACAJUBA', 'LEITE FERMENTADO PAULISTA',
     'PAPEL ALUMINIO BOMPACK 45/7,5', 'EVITA MOFO INSPIRA SONHO DE INFANCIA'],
    ['ACHOC NESCAU LIGHT', 'AGUA SANITARIA 5 LITROS', 'AMEIXA SECA C/CAROCO 100 GRS', 'ATUM RALADO COQUEIRO',
     'AZEITONA TIO PACO 200G', 'BALA CARAMELO', 'COPO PLASUTIL(DUAS ALCAS)', 'PINGA PORTO REAL',
     'COCO RALADO MENINA 100G', 'CR DENTAL COLGATE 50G', 'FAR MANDIOCA AMAFIL', 'FAROFA PRONTA BACON KI FLOR',
     'FAROFA MILHO YOKI', 'PVC BOREDA', 'DOCE GOIABADA PRED 500G', 'MAC NISSIN MIOJO CARNE', 'MAC NISSIN MIOJO GALI',
     'MAC NISSIN MIOJO GALINHA CAIPIRA', 'PAPEL HIG PERSONAL 30M', 'SABAO YPE BARRA', 'SAB FRANCIS CX ROSA VERSAILLES',
     'SANDALIA HAVAI TOP PRETA 35/6'], ['CATCHUP ARISCO PICANTE', 'ERVILHA JUSSARA', 'BISC MARILAN TURMIX CHOC'],
    ['BATATA PALITO BEM BRASIL', 'LEITE CEMIL INTEGRAL', 'LEITE PIRACAJUBA', 'NEOSALDINA COMP', 'RUN MONTILA',
     'SAND HAV SLIM TROPICAL'], ['VINHO JURUBEBA', 'FANTA LAR 2L', 'COCA COLA LATA'],
    ['FAR TRIGO S/ FERMENTO PP', 'FARINHA DE MANDIOCA AMAFIL 500 GRS', 'FAR DE TGO SM C FER PLASTICO',
     'FARINHA DE TRG C/ FERM', 'FARINHA DE TRG SEMOLA'],
    ['ACETONA FARMAX 100ML', 'DES CREME HERBISSIMO FRESH', 'ESCOVA DENTAL LAMOUR MEDIA', 'ESPONJA INOX (REDONDA)',
     'PASTILHA ADESIVA PATO C/3 UNIDADES', 'FERMENTO FERMIX 10G', 'FILTRO PERMANENTE (CAIXA)', 'FUBA SINHA 1KG',
     'LIMPA ALUMINIO', 'MOLHO DE TOMATE FUGINI SACH'], ['SABAO YPE BARRA', 'FER PO ROYAL 100G', 'FER PO ROYAL 250G'],
    ['LING CALABRESA PERDIGAO', 'FILEZINHO PIF PAF (BANDEIJA)'], ['FEIJAO DANDAO 1KG'],
    ['MARG QUALY 500G', 'MORTANDELA SADILAR SADIA 1KG', 'CESTO TELADO 10 LITROS'],
    ['NESTON 3 CEREAIS', 'CHOC NESTLE SUFLAIR 110GRS'], ['ACHOC. TODY 800G'],
    ['PINGA DE RAPADURA', 'DOCE GOIABADA (CASEIRA)', 'FARINHA DE MILHO ARAXA', 'CEBOLA',
     'DES REXONA AEROSOL S/ PERFUME'],
    ['ACUCAR DELTA', 'BISC DUNGA MAIZENA 400G', 'BAND-AID COM 10 UNIDADES', 'DETERGENTE YPE COCO',
     'DETERGENTE YPE MACA', 'DETERGENTE LIQ YPE NEUTRO', 'DORFLEX COMP', 'LEITE CEMIL INTEGRAL',
     'POLVILHO AMAFIL AZEDO', 'POLVILHO AMAFIL DOCE'],
    ['SH CLEAR CASPA', 'SH SEDA LISO EXTREMO', 'CONDICIONADOR SEDA KERAFORCE  QUIMICA', 'BALA FINI (SALADA DE FRUTAS)',
     'SH PALMOLIVE ANTI-ARAMADO', 'SH PALMOLIVE CACHOS', 'SH PALMOLIVE CERAMIDAS', 'SH PALMOLIVE CASTANHO',
     'SH PALMOLIVE LOUROS', 'SH PALMOLIVE KERATINA', 'SH PALMOLIVE NUTRI LISS', 'SH PALMOLIVE PONTAS PERFEITAS',
     'SH PALMOLIVE QUEDA RESIST', 'SH PALMOLIVE SOLAR PROTECT', 'TEMPERO ARISCO COMPLETO', 'TENIS PE AEROSOL ORIGINAL',
     'DESIFENTANTE MARINA EUCALIPTO', 'TENIS PE CANFORADO', 'SAND HAV TREND AZUL 41/42', 'TENIS PE MENTOLADO',
     'TENIS PE BAR TRAD', 'VELAS BELEM 5', 'AMACIANTE CONFORT PURO RELAX', 'H2 OH LIMAO', 'AMAC YPE ENERGIA',
     'SAND HAV SLIM MARFIM 35/36', 'AMAC YPE TERNURA', 'CANJICA AMARELA 500G', 'COND TRESSEME BLINDAGEM',
     'COND MONANGE ANTICASPA', 'NEUTROX', 'SAND HAV SLIM ANIMALIS BEGE 35/36', 'COND TRESSEME DESARRUMADO',
     'COND JOHNSONS NEUTRO', 'BOLO CASEIRO', 'CAFE UTAM (KIT) 500 GRS', 'MAION HELL 500G', 'MAC NINHO SM', 'TRUFAS'],
    ['ABS INTIMUS GEL SUAVE C/ ABAS', 'SAND HAV TOP ROXO 37/8', 'MAION HELL 500G', 'OLEO DE MILHO SINHA',
     'PAPEL ALUMINIO BOMPACK 45/7,5', 'SAB PALMOLLIVE ESFOLIACAO DELICADA'], ['BATATA PALITO PIF PAF'],
    ['LING MINEIRA'], ['SALSICHA PIF PAF'],
    ['MORTANDELA SADILAR SADIA 1KG', 'ABSORVENTE ALWAYS SUAVE', 'SALEIRO', 'LING CALABRESA SADIA'],
    ['CHIC DANNCLETS', 'CJ XICARA LIS', 'CJ XICARA FLORAL', 'TORRADA BAUDUCCO MIX DE CASTANHA', 'RESFEDYL', 'PIRULITO'],
    ['FARINHA DE MANDIOCA AMAFIL 500 GRS', 'FAR DE TGO SM C FER PLASTICO', 'FAR TRIGO S/ FERMENTO PP'],
    ['SEQ VALE DOURO COCO', 'SEQ VALE DOURO LEITE COND'],
    ['ARROZ CORRIPIL 5 KG', 'CARVAO PIU PIU', 'DETERGENTE LIQ YPE NEUTRO'],
    ['IOGURTE VO LOLA 120 GRS (SABORES)', 'IOGURTE PAULISTA  FERMENTADO', 'IOGURTE PAULISTA MOR',
     'SAND HAV TRENT 43/44 PRETO', 'IOGURTE GREGO TRADICIONAL 170 GRS', 'SAND HAV KIDS CARS 33/34 PRETO',
     'INSETICIDA RAID 24 REFIS', 'IOGURTE DANONINHO', 'SAND HAV ATHELTETIC 29/30 AZUL', 'CARIOQUINHA', 'FORMA DE GELO',
     'SAND HAV KIDS MAX HEROIS 33/34 CINZA GELO', 'PAO SOVADO PRAD0', 'PANETONE CHOCOTONE'], ['ROSQUINHA MABEL 400G'],
    ['LING DE LOMBO PIF PAF', 'SUCO CLIGHT TANGERINA', 'SUCO MAIS CAJU 1L'], ['GUARANA SCHIN 2L'],
    ['CREDITO CELULAR', 'PITZZA MASTER GRANDE', 'LASANHA BOLONHESA SADIA'],
    ['CHOC BIS AO LEITE', 'SAND HAV KIDS MAX HEROIS 31/32 PRETO', 'DROPS MENTOS MORANGO', 'DROPS EXTRA FORTE'],
    ['BISC BOA VIDA MORANGO', 'VELAS SAO JUDAS TADEU', 'SH SEDA LISO EXTREMO'],
    ['VELAS SAO JUDAS TADEU', 'ALGODAO APOLO 25 GRS', 'SHAMPOO DOVE REFIL', 'BISC KELY MOR', 'NEUTROX',
     'SAND HAV SLIM ANIMALIS BEGE 35/36', 'COND JONHONS GOTAS BRILHO', 'BISCOITO BAUDUCCO GOTAS CHOC',
     'BALA FINI (TIRAS MORANGO)', 'BALA FINI (TORCAO)', 'TOALHA DE PAPEL BOB'],
    ['DES BATUTA FLORAL', 'DES BATUTA OCEANO', 'LIMPADOR CIF BANHEIRO', 'LIMPEZA PERF UAU LAV/CAMOMILA',
     'LIMPEZA FERF UAU LIRIO/HORT', 'LIMPA VIDROS UAU', 'LINGUICA CANASTRA C/ PIMENTA BIQUINHO',
     'LIMPEZA PESADA UAU CITRUS ESFERAS', 'LIMPA ALUMINIO MIX'],
    ['BISC PAS TEMPO RECH', 'CAFE UTAM EXTRA FORTE 500 GRS', 'DETERGENTE BRILHANTE 2 KG ANTIBAC', 'CHOC CARIBE'],
    ['ARROZ CODIL PLUS T-1', 'FAROFA MANDIOCA KI -FLOR'],
    ['ARROZ CORRIPIL 5 KG', 'CARVAO PIU PIU', 'BAND-AID COM 10 UNIDADES', 'DETERGENTE LIQ YPE NEUTRO'],
    ['LUVA MONALIZA (CAFE)', 'LIXA DE UNHA', 'TORNEIRA', 'PINCA DEPI', 'LIXA  (PES)', 'FANTA LAR 2L', 'CX CERVEJA SKOL',
     'CERVEJA SKOL LATA', 'COCA COLA 2L', 'GUARANA ANT 2L'],
    ['SACO P/FREZER 3 KG BOMPACK', 'AMACIANTE DE CARNE KI DELICIA', 'CHOC KIT KAT', 'KIT PANELINHAS C/3 UNIDADES',
     'COXINHA DA ASA (SADIA)', 'LASANHA PRE-COZIDA', 'MAIONESE SANTA AMALIA SACHE 200G',
     'MISTURA DE BOLO CHO STA AMALIA', 'MISTURA SANTA AMALIA BOLO COCO', 'MIST PAO DE QUEIJO SANTA AMALIA'],
    ['TANG LARANJA CITRUS', 'PEITO AVIVAR'], ['ASSADEIRA RETANGULAR MARINEX 2,9L'],
    ['CHOC BATOM GAR', 'DOCE GOIABADA PRED 1KG', 'COOK  HOUSE', 'LUVA SCOTH MEDIA', 'LUVA MUCAMBO G AMRELA'],
    ['MINI CHICKEN C. VALE', 'LING CALABRESA SADIA'],
    ['MORTANDELA SADILAR SADIA 1KG', 'CHIC TRIDENT FRESH', 'MINI CHICKEN SADIA'],
    ['CANELA EM CASCA 70G', 'COLORIFICO 40G', 'CRAVO KI-DEL', 'LOURO FOLHAS KI-DEL', 'MOLHO INGLES KI-DEL',
     'MOLHO DE PIMENTA 150ML', 'MOLHO DE PIMENTA 500ML', 'MOLHO SHOYU', 'NOZ MOSCADA BOLA KI-DEL',
     'NOZ MOSCADA MOIDA KI-DEL', 'OREGANO KI-DEL', 'PIMENTA DO REINO MOIDA 100G', 'PIMENTA DO REINO EM GRAO 20G',
     'PIMENTA DO REINO MOIDA KI-DEL'], ['BISCOITO OREO CHOC', 'LING DE LOMBO PIF PAF', 'DESODORANTE NIVEA SENSITIVE'],
    ['GUARANA ANTARTICA MINI'], ['AGUA SANITARIA KBOA 2L', 'BISCOITO NEGRESCO ECLIPSE', 'NEOSALDINA COMP'],
    ['FANTA LAR 2L', 'COCA COLA 2L', 'FANTA UVA 2L', 'VINHO CANTINA DA SERRA'], ['TANG LARANJA CITRUS', 'COXA AVIVAR'],
    ['FAR TRIGO S/ FERMENTO PP', 'FARINHA DE TRG SEMOLA', 'FARINHA DE TRG C/ FERM', 'FAR DE TGO SM C FER PLASTICO'],
    ['PILHA DURACEL AAA', 'FUBA MOINHO DAGUA'], ['ABS SEMPRE LIVRE ESPECIAL C/ABAS', 'LANTERNA RECARREGAVEL 9 LEDS'],
    ['ABS SEMPRE LIVRE ESPECIAL C/ABAS', 'AZEITONA RAIOLA S/ CAROCO', 'CHOC BATOM GAR', 'CREME KANECHON',
     'DET PO TIXAN 500G', 'EXTRATO ELEFANTE 340G', 'MAION HELL 250G', 'PIRULITO BIG CHERRY', 'PIRULITO SORTIDO']
]

'''
#inc = 50


vendaProdMat = loadCSV()
transactions = []

for i in range(len(vendaProdMat)):
    aux = []
    for j in range(1, len(vendaProdMat[i])):
        aux.append(vendaProdMat[i][j])
    transactions.append(aux)
    print(len(transactions))
    #if(i == inc):
       # itemsets, rules = apriori(transactions, min_support=0.3, min_confidence=0.5)
        #print(rules)
        #inc = inc + 50
        #transactions = []

print(transactions)

'''
results = list(apriori(transactions))
print(results)